# See also https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ 

name: "Build and upload to PyPI"
on:
  release:
    types: ["published"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.x"

      - name: "Install packaging tools"
        run: "python -m pip install --upgrade build twine"

      - name: "Build dist package"
        run: "python -m build"

      - name: "Upload to PyPI"
        run: "python -m twine upload dist/*"
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: "${{ secrets.PYPI_API_TOKEN }}"
